# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Migrate < Formula
  desc "Database migrations CLI (fork with Azure Entra ID auth for SQL Server)"
  homepage "https://github.com/RobbertH/migrate"
  version "4.19.1-entra.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RobbertH/migrate/releases/download/v4.19.1-entra.1/migrate.darwin-amd64.tar.gz"
      sha256 "aef3e8652473bfcf81b4ff87c33a0f2fc2d62379a652a7c90bc864feafafc368"

      define_method(:install) do
        bin.install "migrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RobbertH/migrate/releases/download/v4.19.1-entra.1/migrate.darwin-arm64.tar.gz"
      sha256 "657fbe2edb293fc787d6a0fb8f94fe358fb86f0d1faf27ae74748a07fa39281f"

      define_method(:install) do
        bin.install "migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RobbertH/migrate/releases/download/v4.19.1-entra.1/migrate.linux-amd64.tar.gz"
      sha256 "2029218f5fe05dfe213d944ed4b7b7b9ff449c6c6ccad59437083d346399bc1d"
      define_method(:install) do
        bin.install "migrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RobbertH/migrate/releases/download/v4.19.1-entra.1/migrate.linux-arm64.tar.gz"
      sha256 "dd228c859b2be77b135375ae0c0739e7039982263ffa1abf40ef138252d8347c"
      define_method(:install) do
        bin.install "migrate"
      end
    end
  end

  conflicts_with "golang-migrate"

  test do
    system "#{bin}/migrate", "-version"
  end
end
